<?php

namespace app\modules\post\models;

use Yii;
use yii\db\ActiveRecord;
/**
 * This is the model class for table "{{%tag}}".
 *
 * @property string $id
 * @property string $tag
 * @property string $frequency
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Posttag[] $posttag
 */
class Tag extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tag}}';
    }

    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tag'], 'required'],
            [['frequency'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['tag'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'tag' => Yii::t('app', 'Tag'),
            'frequency' => Yii::t('app', 'Frequency'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    public function beforeValidate()
    {
        if ($this->isNewRecord){
            $this->frequency    =   0;
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPosttag()
    {
        return $this->hasMany(Posttag::className(), ['post_id' => 'id']);
    }
}
