<?php
namespace app\components\Helper;

class Stopwords{
    
    private static $faStopWordsList =   [
        "من",
        "تو",
        "او",
        "ما",
        "شما",
        "ایشان",
        "آنها",
        "آن‌ها",
        "چه",
        "کسی",
        "چیزی",
        "همه",
        "یا",
        "اما",
        "از",
        "به",
        "تا",
        "که",
        "اگر",
        "و",
        "چون",
        "با",
        "برای",
        "در",
        "روی",
        "بین",
        "تحت",
        "کنار",
        "بدون",
        "طبق",
        "چگونه",
        "فقط",
        "بنابرین",
        "تو",
        "در",
    ];


    private static $enStopWordsList   =   [
        "a",
        "about",
        "above",
        "after",
        "again",
        "against",
        "all",
        "am",
        "an",
        "and",
        "any",
        "are",
        "aren't",
        "as",
        "at",
        "be",
        "because",
        "been",
        "before",
        "being",
        "below",
        "between",
        "both",
        "but",
        "by",
        "can't",
        "cannot",
        "could",
        "couldn't",
        "did",
        "didn't",
        "do",
        "does",
        "doesn't",
        "doing",
        "don't",
        "down",
        "during",
        "each",
        "few",
        "for",
        "from",
        "further",
        "had",
        "hadn't",
        "has",
        "hasn't",
        "have",
        "haven't",
        "having",
        "he",
        "he'd",
        "he'll",
        "he's",
        "her",
        "here",
        "here's",
        "hers",
        "herself",
        "him",
        "himself",
        "his",
        "how",
        "how's",
        "i",
        "i'd",
        "i'll",
        "i'm",
        "i've",
        "if",
        "in",
        "into",
        "is",
        "isn't",
        "it",
        "it's",
        "its",
        "itself",
        "let's",
        "me",
        "more",
        "most",
        "mustn't",
        "my",
        "myself",
        "no",
        "nor",
        "not",
        "of",
        "off",
        "on",
        "once",
        "only",
        "or",
        "other",
        "ought",
        "our",
        "ours	",
        "ourselves",
        "out",
        "over",
        "own",
        "same",
        "shan't",
        "she",
        "she'd",
        "she'll",
        "she's",
        "should",
        "shouldn't",
        "so",
        "some",
        "such",
        "than",
        "that",
        "that's",
        "the",
        "their",
        "theirs",
        "them",
        "themselves",
        "then",
        "there",
        "there's",
        "these",
        "they",
        "they'd",
        "they'll",
        "they're",
        "they've",
        "this",
        "those",
        "through",
        "to",
        "too",
        "under",
        "until",
        "up",
        "very",
        "was",
        "wasn't",
        "we",
        "we'd",
        "we'll",
        "we're",
        "we've",
        "were",
        "weren't",
        "what",
        "what's",
        "when",
        "when's",
        "where",
        "where's",
        "which",
        "while",
        "who",
        "who's",
        "whom",
        "why",
        "why's",
        "with",
        "won't",
        "would",
        "wouldn't",
        "you",
        "you'd",
        "you'll",
        "you're",
        "you've",
        "your",
        "yours",
        "yourself",
        "yourselves"
   ];
    
   private static function getValidCharacters()
   {
//       آ ا ب پ ت ث ج چ ح خ د ذ ر ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ه ی
       $persian =   [
           'آ',
           'ا',
           'ب',
           'پ',
           'ت',
           'ث',
           'ج',
           'چ',
           'ح',
           'خ',
           'د',
           'ذ',
           'ر',
           'ز',
           'ژ',
           'س',
           'ش',
           'ص',
           'ض',
           'ط',
           'ظ',
           'ع',
           'غ',
           'ف',
           'ق',
           'ک',
           'گ',
           'ل',
           'م',
           'ن',
           'و',
           'ه',
           'ی',
       ];
       
       $english =   [
           'a',
           'b',
           'c',
           'd',
           'e',
           'f',
           'g',
           'h',
           'i',
           'j',
           'k',
           'l',
           'm',
           'n',
           'o',
           'p',
           'q',
           'r',
           's',
           't',
           'u',
           'v',
           'w',
           'x',
           'y',
           'z'
       ];
       
       $number  =   [0,1,2,3,4,5,6,7,8,9,'0','1','2','3','4','5','6','7','8','9'];
       $chars   =   ['-'];
       return array_merge($persian,$english,$number,$chars);
   }
   
   public static function removeUnvalidCharacters($string)
   {
       $regex  = sprintf('/[^%s]/u', preg_quote(join(self::getValidCharacters()), '/'));
       return preg_replace($regex, '', $string);
   }

    /**
     * 
     * @param array $words
     * @return array
     */
    public static function purifierText(array $words){
        $pure = array_diff($words, self::$faStopWordsList);
        $pure = array_diff($pure, self::$enStopWordsList);
        return $pure;
    }
    
    public static function purgeLongWord(array $words,$len = 40){
        $pure   =   [];
        foreach ($words as $word){
            if (strlen($word) < $len){
                $pure[] =   $word;
            }
        }
        return $pure;
    }
}

