<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2015-07-14 15:07:29
 */
return [
    'main' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [
            'afba5b4a24c63838e3d765beb2d13f785.js',
        ],
        'css' => [
            'a7f40d9c45e0b07ce0cdba159573acc45.css',
        ],
    ],
    'editor' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [
            'b7b36ff806bbbfc4057058232df04060e.js',
        ],
        'css' => [
            'bc44442bb668f454bf5cb2325d80f1fa8.css',
        ],
    ],
    'show' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [],
        'css' => [
            'cc44442bb668f454bf5cb2325d80f1fa8.css',
        ],
    ],
    'icheck' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [
            'ddfaf0fe44769e1510387ad9fc6001482.js',
        ],
        'css' => [
            'd4301a2ad48dfe68954bcda9e8136a5f3.css',
        ],
    ],
    'jasny' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [
            'e76bd16160c8217aff32ce45337a8f681.js',
        ],
        'css' => [
            'eb314a5d8b4926f0cdaf025b8885089c3.css',
        ],
    ],
    'switch' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [],
        'css' => [
            'f7c1f3757ce1f35cf63a52f95718c763f.css',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'main',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'main',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'main',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'main',
        ],
    ],
    'app\\assets\\FontAwesomeAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'main',
        ],
    ],
    'app\\assets\\InitAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'app\\assets\\FontAwesomeAssets',
            'main',
        ],
    ],
    'app\\assets\\WowAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'main',
        ],
    ],
    'app\\assets\\MainAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\InitAssets',
            'app\\assets\\WowAssets',
            'main',
        ],
    ],
    'app\\assets\\UnderscoreAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'editor',
        ],
    ],
    'app\\assets\\SanitizeAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'editor',
        ],
    ],
    'app\\assets\\DanteAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\UnderscoreAssets',
            'app\\assets\\SanitizeAssets',
            'app\\assets\\MainAssets',
            'editor',
        ],
    ],
    'app\\assets\\CustomEditorAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\MainAssets',
            'app\\assets\\DanteAssets',
            'editor',
        ],
    ],
    'app\\assets\\ShowPostAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\MainAssets',
            'show',
        ],
    ],
    'app\\assets\\ICheckAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\MainAssets',
            'icheck',
        ],
    ],
    'app\\assets\\JasnyBootstrapAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\MainAssets',
            'jasny',
        ],
    ],
    'app\\assets\\BootstrapSwitchAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\MainAssets',
            'switch',
        ],
    ],
];